name: Build LaTeX document

on: 
  push:
    branches: 
      - main    

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: FAST-Algorithm.tex

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0