name: Build LaTeX document

on: 
  push:
    branches: 
      - main    

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2.4.2
     
      - name: LaTeX compilation
        uses: dante-ev/latex-action@2021-A
        with:
          working_directory: documentation/src
          root_file: FAST-Algorithm.tex

      - name: Check pdf files
        run: |
          set -e
          file documentation/src/FAST-Algorithm.pdf | grep -q ' PDF '